CHANGELOG.md
docs/jupiterone.md
package.json
src/steps/active-directory/index.ts
src/steps/intune/constants.ts
src/steps/intune/steps/applications/index.ts
src/steps/intune/steps/deviceConfigurationsAndFindings/index.ts
src/steps/intune/steps/devices/__tests__/__snapshots__/index.test.ts.snap
src/steps/intune/steps/devices/__tests__/index.test.ts
yarn.lock

Added back now that @austinkelleher fixed the sdk bug -- https://github.com/JupiterOne/sdk/pull/430

Make devices hosts as well

---

docs/development.md

Idk if you think this is worth adding to the `changelog` or not.  My thinking is that so long as it is in the master branch, engineers will see it which is all that matters here.

Add some Intune development instructions

---

CHANGELOG.md
src/steps/intune/steps/compliancePoliciesAndFindings/index.ts
src/steps/intune/steps/deviceConfigurationsAndFindings/index.ts

A few band-aids for duplicate key errors.

Duplicate compliance keys

---

docs/development.md
docs/jupiterone.md

Some updates after working with @mknoedel to get the integration running in a new environment. Hopefully, this makes things a bit clearer, adopting some terminology I picked up in the MS docs.

Clarify development and integration documentation

---

.prettierignore
package.json
src/index.ts
src/steps/active-directory/__tests__/converters.test.ts
src/steps/intune/constants.ts
src/steps/intune/steps/applications/__tests__/index.test.ts
src/steps/intune/steps/compliancePoliciesAndFindings/__tests__/index.test.ts
src/steps/intune/steps/compliancePoliciesAndFindings/index.ts
src/steps/intune/steps/deviceConfigurationsAndFindings/__tests__/fixtures/exampleDeviceStatus.ts
src/steps/intune/steps/deviceConfigurationsAndFindings/__tests__/index.test.ts
src/steps/intune/steps/deviceConfigurationsAndFindings/index.ts
src/steps/intune/steps/devices/__tests__/index.test.ts
src/steps/intune/utils.test.ts
src/steps/intune/utils.ts
src/types.ts

This PR is the result of running `yarn format`.

Running yarn format

---

CHANGELOG.md
package.json
src/steps/intune/steps/devices/__tests__/converters.test.ts
src/steps/intune/steps/devices/converters.ts
yarn.lock

**BREAKING** - Update `_type` of `smartphone` entity to `user_endpoint`
when the device has a `deviceType` with value `windowsRT`

INT-2833 - Update `_type` value of `smartphone` entity in case

---

.github/workflows/build.yml
.github/workflows/codeql-analysis.yml
.github/workflows/questions.yml
.prettierignore
jupiterone/questions/questions.yaml
package.json
tsconfig.dist.json

** This PR requires extra review **
** The /dist for this integration has changed, it shouldn't be breaking, but we should still be careful**
This PR updates workflows in graph-microsoft-365, adds the codeql-analysis workflow, and questions workflow. It adds managed questions to the public repo.
Other miscellaneous or formatting changes may be included.

INT-3469 Add Questions, Workflows, Misc QoL updates

---

CHANGELOG.md
package.json

Release 6.1.2 for `graph-microsoft-365`.

Release 6.1.2

---

CHANGELOG.md
package.json
yarn.lock

- Remove unused dep, bump peer dep
- Update CHANGELOG
- v6.1.4

release 6.1.4

---

src/steps/intune/steps/devices/__tests__/__snapshots__/index.test.ts.snap
src/steps/intune/steps/devices/converters.ts

This PR add a check for `"Unknown"` for the `jailBroken` property. If the value is `"Unknown"` then the property is set to `undefined`.

INT-4517 Handle Unknown case for jailbroken property

---

CHANGELOG.md
package.json

- Updating CHANGELOG
- v6.4.2-beta.2

release 6.4.2 beta.2

---

src/ms-graph/client.ts

This PR reverts two beta changes that are not needed:
- increasing the timeout by 15 seconds
- adding detailed logging

revert beta testing changes

---

CHANGELOG.md
package.json

release 6.4.4

---

CHANGELOG.md
package.json
src/validateInvocation.test.ts
src/validateInvocation.ts

- add better error messaging
- imprv error messaging for validateInvocation

int 6317 add better error log

---

.github/workflows/build.yml
.github/workflows/integration-deployment.yml
package.json
src/steps/intune/clients/deviceManagementIntuneClient.ts
src/steps/intune/steps/applications/index.ts
src/steps/intune/types.ts
yarn.lock

https://techcommunity.microsoft.com/t5/intune-customer-success/support-tip-retrieving-intune-apps-reporting-data-from-microsoft/ba-p/3851578

Fixed beta endpoint 

---

package.json

Added postversion script

---

src/index.ts

fix: export ingestionConfig

---

src/utils/__tests__/getStepStartStates.test.ts
src/utils/getStepStartStates.ts

IINT-10049: disable Managed Applications step temporarily

---

src/utils/__tests__/getStepStartStates.test.ts
src/utils/getStepStartStates.ts

INT-8991: re enable managed applications step

---

src/steps/intune/steps/applications/index.ts

INT-8991: add try catch in device installation fetch

---

src/instanceConfigFields.ts
src/steps/intune/steps/compliancePoliciesAndFindings/index.ts
src/steps/intune/steps/deviceConfigurationsAndFindings/index.ts
src/steps/intune/types.ts
src/steps/intune/utils.ts
src/types.ts
src/validateInvocation.ts

Add vuln filters

---

src/steps/active-directory/__tests__/__recordings__/iterateUsers404_1274458897/recording.har
src/steps/active-directory/__tests__/client.test.ts
src/steps/active-directory/clients/directoryClient.ts
src/steps/active-directory/users/converters.ts

Added properties to user

---

src/steps/active-directory/clients/directoryClient.ts

Remove confusing log
